In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv('Iris.csv', index_col=0)

In [3]:
data.head(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
6             5.4           3.9            1.7           0.4  Iris-setosa
7             4.6           3.4            1.4           0.3  Iris-setosa
8             5.0           3.4            1.5           0.2  Iris-setosa
9             4.4           2.9            1.4           0.2  Iris-setosa
10            4.9           3.1            1.5           0.1  Iris-setosa

In [4]:
data.tail(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
141            6.7           3.1            5.6           2.4  Iris-virginica
142            6.9           3.1            5.1           2.3  Iris-virginica
143            5.8           2.7            5.1           1.9  Iris-virginica
144            6.8           3.2            5.9           2.3  Iris-virginica
145            6.7           3.3            5.7           2.5  Iris-virginica
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [6]:
data.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [7]:
np.unique(data['SepalLengthCm'])

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [8]:
np.unique(data['SepalWidthCm'])

array([2. , 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3,
       3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.4])

In [9]:
np.unique(data['PetalLengthCm'])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.9, 3. , 3.3, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.3,
       6.4, 6.6, 6.7, 6.9])

In [10]:
np.unique(data['PetalWidthCm'])

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
       1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5])

In [11]:
np.unique(data['Species'])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [12]:
data.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [13]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [14]:
data.memory_usage()

Index            1200
SepalLengthCm    1200
SepalWidthCm     1200
PetalLengthCm    1200
PetalWidthCm     1200
Species          1200
dtype: int64

In [15]:
data.ndim

2

In [16]:
data.loc[:, 'SepalWidthCm']

Id
1      3.5
2      3.0
3      3.2
4      3.1
5      3.6
      ... 
146    3.0
147    2.5
148    3.0
149    3.4
150    3.0
Name: SepalWidthCm, Length: 150, dtype: float64

In [17]:
dt=data.copy()

In [18]:
pd.crosstab(index=dt['Species'], columns= 'count', dropna= True)

col_0            count
Species               
Iris-setosa         50
Iris-versicolor     50
Iris-virginica      50

In [19]:
pd.crosstab(index=dt['Species'], columns=dt['SepalWidthCm'], dropna=True)

SepalWidthCm     2.0  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.0  ...  3.4  \
Species                                                            ...        
Iris-setosa        0    0    1    0    0    0    0    0    1    6  ...    9   
Iris-versicolor    1    2    3    3    4    3    5    6    7    8  ...    1   
Iris-virginica     0    1    0    0    4    2    4    8    2   12  ...    2   

SepalWidthCm     3.5  3.6  3.7  3.8  3.9  4.0  4.1  4.2  4.4  
Species                                                       
Iris-setosa        6    2    3    4    2    1    1    1    1  
Iris-versicolor    0    0    0    0    0    0    0    0    0  
Iris-virginica     0    1    0    2    0    0    0    0    0  

[3 rows x 23 columns]

In [20]:
pd.crosstab(index=dt['Species'],columns=dt['SepalWidthCm'], normalize= True, dropna= True)

SepalWidthCm          2.0       2.2       2.3   2.4       2.5       2.6  \
Species                                                                   
Iris-setosa      0.000000  0.000000  0.006667  0.00  0.000000  0.000000   
Iris-versicolor  0.006667  0.013333  0.020000  0.02  0.026667  0.020000   
Iris-virginica   0.000000  0.006667  0.000000  0.00  0.026667  0.013333   

SepalWidthCm          2.7       2.8       2.9       3.0  ...       3.4   3.5  \
Species                                                  ...                   
Iris-setosa      0.000000  0.000000  0.006667  0.040000  ...  0.060000  0.04   
Iris-versicolor  0.033333  0.040000  0.046667  0.053333  ...  0.006667  0.00   
Iris-virginica   0.026667  0.053333  0.013333  0.080000  ...  0.013333  0.00   

SepalWidthCm          3.6   3.7       3.8       3.9       4.0       4.1  \
Species                                                                   
Iris-setosa      0.013333  0.02  0.026667  0.013333  0.006667  0.006667   
Iris-versicolor  0.000000  0.00  0.000000  0.000000  0.000000  0.000000   
Iris-virginica   0.006667  0.00  0.013333  0.000000  0.000000  0.000000   

SepalWidthCm          4.2       4.4  
Species                              
Iris-setosa      0.006667  0.006667  
Iris-versicolor  0.000000  0.000000  
Iris-virginica   0.000000  0.000000  

[3 rows x 23 columns]

In [21]:
pd.crosstab(index=dt['Species'], columns= dt['SepalWidthCm'], margins=True, normalize= True, dropna=True)

SepalWidthCm          2.0       2.2       2.3   2.4       2.5       2.6  \
Species                                                                   
Iris-setosa      0.000000  0.000000  0.006667  0.00  0.000000  0.000000   
Iris-versicolor  0.006667  0.013333  0.020000  0.02  0.026667  0.020000   
Iris-virginica   0.000000  0.006667  0.000000  0.00  0.026667  0.013333   
All              0.006667  0.020000  0.026667  0.02  0.053333  0.033333   

SepalWidthCm          2.7       2.8       2.9       3.0  ...   3.5       3.6  \
Species                                                  ...                   
Iris-setosa      0.000000  0.000000  0.006667  0.040000  ...  0.04  0.013333   
Iris-versicolor  0.033333  0.040000  0.046667  0.053333  ...  0.00  0.000000   
Iris-virginica   0.026667  0.053333  0.013333  0.080000  ...  0.00  0.006667   
All              0.060000  0.093333  0.066667  0.173333  ...  0.04  0.020000   

SepalWidthCm      3.7       3.8       3.9       4.0       4.1       4.2  \
Species                                                                   
Iris-setosa      0.02  0.026667  0.013333  0.006667  0.006667  0.006667   
Iris-versicolor  0.00  0.000000  0.000000  0.000000  0.000000  0.000000   
Iris-virginica   0.00  0.013333  0.000000  0.000000  0.000000  0.000000   
All              0.02  0.040000  0.013333  0.006667  0.006667  0.006667   

SepalWidthCm          4.4       All  
Species                              
Iris-setosa      0.006667  0.333333  
Iris-versicolor  0.000000  0.333333  
Iris-virginica   0.000000  0.333333  
All              0.006667  1.000000  

[4 rows x 24 columns]

In [22]:
pd.crosstab(index= dt['Species'], columns= dt['SepalWidthCm'], margins=True, dropna= True, normalize='index')

SepalWidthCm          2.0   2.2       2.3   2.4       2.5       2.6   2.7  \
Species                                                                     
Iris-setosa      0.000000  0.00  0.020000  0.00  0.000000  0.000000  0.00   
Iris-versicolor  0.020000  0.04  0.060000  0.06  0.080000  0.060000  0.10   
Iris-virginica   0.000000  0.02  0.000000  0.00  0.080000  0.040000  0.08   
All              0.006667  0.02  0.026667  0.02  0.053333  0.033333  0.06   

SepalWidthCm          2.8       2.9       3.0  ...   3.4   3.5   3.6   3.7  \
Species                                        ...                           
Iris-setosa      0.000000  0.020000  0.120000  ...  0.18  0.12  0.04  0.06   
Iris-versicolor  0.120000  0.140000  0.160000  ...  0.02  0.00  0.00  0.00   
Iris-virginica   0.160000  0.040000  0.240000  ...  0.04  0.00  0.02  0.00   
All              0.093333  0.066667  0.173333  ...  0.08  0.04  0.02  0.02   

SepalWidthCm      3.8       3.9       4.0       4.1       4.2       4.4  
Species                                                                  
Iris-setosa      0.08  0.040000  0.020000  0.020000  0.020000  0.020000  
Iris-versicolor  0.00  0.000000  0.000000  0.000000  0.000000  0.000000  
Iris-virginica   0.04  0.000000  0.000000  0.000000  0.000000  0.000000  
All              0.04  0.013333  0.006667  0.006667  0.006667  0.006667  

[4 rows x 23 columns]

In [23]:
ndt=dt.select_dtypes(exclude=[object])

In [24]:
corrmat= ndt.corr()
corrmat

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       1.000000     -0.109369       0.871754      0.817954
SepalWidthCm       -0.109369      1.000000      -0.420516     -0.356544
PetalLengthCm       0.871754     -0.420516       1.000000      0.962757
PetalWidthCm        0.817954     -0.356544       0.962757      1.000000